services:
  database:
    image: postgres
    ports:
      - 5001:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
  cache:
    image: redis
    ports:
      - 5002:6379
volumes:
  pgdata: